In [97]:
import pandas as pd
df= pd.read_excel(r"C:\Users\janan\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [98]:
df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [99]:
df["Last_Name"]=df["Last_Name"].str.strip()
df

C:\Users\janan\AppData\Local\Temp\ipykernel_14736\3403433179.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"]=df["Last_Name"].str.strip()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [100]:
df["Last_Name"]=df["Last_Name"].str.strip("._/")
df

C:\Users\janan\AppData\Local\Temp\ipykernel_14736\3542657465.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last_Name"]=df["Last_Name"].str.strip("._/")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [101]:
df["Phone_Number"]=df["Phone_Number"].str.replace("/","")
df["Phone_Number"]=df["Phone_Number"].str.replace("-","")
df["Phone_Number"]=df["Phone_Number"].str.replace("|","")
df

C:\Users\janan\AppData\Local\Temp\ipykernel_14736\165856190.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"]=df["Phone_Number"].str.replace("/","")
C:\Users\janan\AppData\Local\Temp\ipykernel_14736\165856190.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"]=df["Phone_Number"].str.replace("-","")
C:\Users\janan\AppData\Local\Temp\ipykernel_14736\165856190.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Phone_Number"]=df["Phone_Number"].str.replace("|","")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True

In [102]:
df.drop(columns=["Address"])

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,Yes,No,True
1,1002,Abed,Nadir,1236439775,No,Yes,False
2,1003,Walter,White,NaN,N,NaN,True
3,1004,Dwight,Schrute,1235432345,Yes,Y,True
4,1005,Jon,Snow,8766783469,Y,No,True
5,1006,Ron,Swanson,3047622467,Yes,Yes,True
6,1007,Jeff,Winger,NaN,No,No,False
7,1008,Sherlock,Holmes,8766783469,N,No,False
8,1009,Gandalf,NaN,Na,Yes,NaN,False
9,1010,Peter,Parker,1235455421,Yes,No,True
10,1011,Samwise,Gamgee,NaN,Yes,No,True
11,1012,Harry,Potter,NaN,Y,NaN,True
12,1013,Don,Draper,1235432345,Yes,N,False
13,1014,Leslie,Knope,8766783469,Yes,No,False
14,1015,Toby,Flenderson,3047622467,N,No,False
15,1016,Ron,Weasley,1235455421,No,N,False
16,1017,Michael,Scott,1236439775,Yes,No,False
17,1018,Clark,Kent,NaN,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,Yes,N,True

In [103]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")
df

C:\Users\janan\AppData\Local\Temp\ipykernel_14736\4094285952.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")
C:\Users\janan\AppData\Local\Temp\ipykernel_14736\4094285952.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,No,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Yes,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,N,No,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Y,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,No,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,No,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [104]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")
df

C:\Users\janan\AppData\Local\Temp\ipykernel_14736\1373516867.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")
C:\Users\janan\AppData\Local\Temp\ipykernel_14736\1373516867.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,False
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,True
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Y,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,Na,N/a,N/a,Y,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [105]:
df=df[df["Do_Not_Contact"]!="Y"]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
6,1007,Jeff,Winger,NaN,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,NaN,Na,123 Middle Earth,Y,NaN,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [106]:
df=df.fillna(" ")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
2,1003,Walter,White,,298 Drugs Driveway,N,,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,,Na,123 Middle Earth,Y,,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [107]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace(" ","N")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
2,1003,Walter,White,,298 Drugs Driveway,N,N,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,,Na,123 Middle Earth,Y,N,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,N,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,N,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [108]:
df["Phone_Number"]=df["Phone_Number"].str.replace("Na","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
2,1003,Walter,White,,298 Drugs Driveway,N,N,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
6,1007,Jeff,Winger,,1209 South Street,N,N,False
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,,,123 Middle Earth,Y,N,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,N,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
17,1018,Clark,Kent,,3498 Super Lane,Y,N,True
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [109]:
df=df[df["Phone_Number"]!=" "]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
8,1009,Gandalf,,,123 Middle Earth,Y,N,False
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True

In [110]:
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True
1,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True
2,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False
3,1009,Gandalf,,,123 Middle Earth,Y,N,False
4,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True
5,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False
6,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False
7,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False
8,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False
9,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False
10,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True